name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    name: test build
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Test
      run: make test
    - name: Run linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
        args: -E=gofmt --timeout=30m0s
